### ISSUE TITLE
Replace `asyncapi/types` with jasyncapi types

### ISSUE THREAD

**Issue by stavshamir** [springwolf/springwolf-core#33]
### Motivation
Currently, the project uses in-house implementation of the various asyncapi types (such as `Channel`, `Operation` etc.). 
This in-house implementation is problematic due to:
1. There are many bindings missing for most of the protocols. Actually only kafka bindings were implemented. For more plugins to be created, we need the bindings for them.
2. It repeats the great job already done by @Pakisan in [jasyncapi](https://github.com/asyncapi/jasyncapi).

There for, it would be a great step to replace all those in-house implementations (from `asyncapi/types` package) with the types provided by `jasyncapi-core`.

### Tasks
- [ ] Add `jasyncapi-core` dependency
- [ ] Replace all in-house implementations with provided types from `jasyncapi`. Many have the same names so the switch should be rather smooth, but I did rely on some custom builders, constructors and json serializations that may require additional attention.
- [ ] Fix the tests and verify all pass
- [ ] Remove local `asyncapi/tests` package (except for `ProducerData`, which may not belong there, but its future location may be decided later on).
- [ ] Release local snapshot version, and update the kafka plugin. After it is updated, I will release an actual version.

**Comment by kalarani** [comment]
Sure @stavshamir . I'll take a look.
